package main

import "fmt"
/*
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/
func findTheDifference(s string, t string) byte {
        smap := make([]int,26)
        for i:=0;i<len(t);i++ {
                smap[t[i]-'a']+=1
        }
        for i:=0;i<len(s);i++ {
                smap[s[i]-'a']-=1
        }
        for k,v := range smap {
                if v == 1 {
                        return byte('a' + k)
                }
        }
        return 0
}

func main() {
        fmt.Println(string(findTheDifference("abcd","abcde")))
}
